name: museum_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ganti ini agar kompatibel dengan Dart versi sekarang

dependencies:
  flutter:
    sdk: flutter

  # Icons & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0 # Cukup satu kali saja

  # UI & Utilities
  flutter_staggered_grid_view: ^0.6.2
  image_picker: ^0.8.7+5
  gap: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
